AWSTemplateFormatVersion: '2010-09-09'

Description: Custom Resource template with YAML -Custom Resource Depends on base/1-vpc-cfn.yml, rds/1-s3-lambda-deploy-cfn.yml, base/2-sg-cfn.yml, rds/2-natgw-cfn.yml, rds/3-lambda-cfn.yml, rds/3-rds-postgres-cfn.yml

Parameters:
  VPCName:
    Description: Target VPC Stack Name
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: debugroom-mynavi-sonarqube-cfn-vpc

Resources:
  LambdaTrigger:
    Type: Custom::LambdaTrigger
    Properties:
      ServiceToken:
        Fn::ImportValue: !Sub ${VPCName}-LamdaForCreateUserInRdsArn
      Region: !Ref "AWS::Region"