AWSTemplateFormatVersion: '2010-09-09'

Description: Sonarqube server target group template with YAML - ALB Target group.  Depends On base/1-vpc-cfn.yml, base/2-sg-cfn.yml, base/3-alb-cfn.yml.

Parameters:
  VPCName:
    Description: Target VPC Name
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: debugroom-mynavi-sonarqube-cfn-vpc
  EnvType:
    Description: Which environments to deploy your service.
    Type: String
    AllowedValues: ["Dev", "Production"]
    Default: Dev

Mappings:
  DeployEnvironmentMap:
    Production:
      #      "Protocol": "HTTPS"
      #      "Port": 443
      "Protocol": "HTTP"
      "Port": 80
    Dev:
      "Protocol": "HTTP"
      "Port": 80

Resources:
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      # Target group name cannot be longer than '32' characters
      Name: sonarqube-cfn-tg
      VpcId:
        Fn::ImportValue: !Sub ${VPCName}-VPCID
      Port: !FindInMap [DeployEnvironmentMap, !Ref EnvType, Port]
      Protocol: !FindInMap [DeployEnvironmentMap, !Ref EnvType, Protocol]
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 60
      HealthyThresholdCount: 2
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '60'

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      Conditions:
        - Field: path-pattern
          PathPatternConfig:
            Values:
              - /*
      ListenerArn:
        Fn::ImportValue: !Sub ${VPCName}-PublicALB-Listener
      Priority: 1

Outputs:
  TargetGroup:
    Description: TargetGroup Service
    Value: !Ref TargetGroup
    Export:
      Name: !Sub ${VPCName}-SonarQube-TargetGroup